from collections.abc import Callable
from typing import Any

class CacheInfo:
    @property
    def hits(self) -> int: ...
    @property
    def misses(self) -> int: ...
    @property
    def max_size(self) -> int: ...
    @property
    def current_size(self) -> int: ...
    def __repr__(self) -> str: ...

class SharedCacheInfo:
    @property
    def hits(self) -> int: ...
    @property
    def misses(self) -> int: ...
    @property
    def max_size(self) -> int: ...
    @property
    def current_size(self) -> int: ...
    @property
    def oversize_skips(self) -> int: ...
    def __repr__(self) -> str: ...

class CachedFunction:
    def __init__(
        self,
        fn_obj: Callable[..., Any],
        strategy: int,
        max_size: int,
        ttl: float | None = None,
    ) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any | None: ...
    def set(self, value: Any, *args: Any, **kwargs: Any) -> None: ...
    def cache_info(self) -> CacheInfo: ...
    def cache_clear(self) -> None: ...

class SharedCachedFunction:
    def __init__(
        self,
        fn_obj: Callable[..., Any],
        strategy: int,
        max_size: int,
        ttl: float | None = None,
        max_key_size: int = 512,
        max_value_size: int = 4096,
        shm_name: str | None = None,
    ) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any | None: ...
    def set(self, value: Any, *args: Any, **kwargs: Any) -> None: ...
    def cache_info(self) -> SharedCacheInfo: ...
    def cache_clear(self) -> None: ...
